FROM golang:alpine AS builder

ADD . /go/src/github.com/namely/grpc-to-grpc
WORKDIR /go/src/github.com/namely/grpc-to-grpc
RUN go build -o /usr/local/bin/joke-gw ./cmd/gateway

FROM alpine
COPY --from=builder /usr/local/bin/joke-gw /usr/local/bin/joke-gw

ENV GRPC_ADDR joke-grpc:50051
ENV HTTP_PORT 80

CMD ["joke-gw"]
